sh run_demo_linreg.sh 1
sh run_demo_linreg.sh 2
sh run_demo_linreg.sh 3
sh run_demo_linreg.sh 4
sh run_demo_linreg.sh 4
sh run_demo_linreg.sh 5
sh run_demo_linreg.sh 6
sh run_demo_linreg.sh 7
sh run_demo_linreg.sh 8
sh run_demo_linreg.sh 9
sh run_demo_linreg.sh 10
sh run_demo_linreg.sh 11
sh run_demo_linreg.sh 12
sh run_demo_linreg.sh 13
sh run_demo_linreg.sh 14
sh run_demo_linreg.sh 15
sh run_demo_linreg.sh 16
sh run_demo_linreg.sh 17
sh run_demo_linreg.sh 18
sh run_demo_linreg.sh 19
sh run_demo_linreg.sh 20
sh run_demo_linreg.sh 21
sh run_demo_linreg.sh 22
sh run_demo_linreg.sh 23
sh run_demo_linreg.sh 24
sh run_demo_linreg.sh 25
sh run_demo_linreg.sh 26
sh run_demo_linreg.sh 27
sh run_demo_linreg.sh 28
sh run_demo_linreg.sh 29
